# -*- coding: utf-8 -*-
"""bollTSClass.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y24Qw0giYJojj79vVfqdFxf4wxQyXDH0
"""

import numpy as np
import pandas as pd
import talib
import yfinance as yf
from datetime import datetime
import matplotlib.pyplot as plt
import statistics
from parentTSClass import parentTSClass

class bollTSClass(parentTSClass):
    # 布林通道的週期和標準差倍數
    def __init__(self, target_stock, start_date, end_date, stopLoss, timeperiod=20, nbdevup=2, nbdevdn=2):
        # 呼叫父類別的初始化方法
        super().__init__(target_stock, start_date, end_date, stopLoss)
        self.timeperiod = timeperiod 
        self.nbdevup = nbdevup      
        self.nbdevdn = nbdevdn      

    def tradingStrategy(self, target_stock=0, start_date=0, end_date=0, stopLoss=0):
        target_stock = self.target_stock
        start_date = self.start_date
        end_date = self.end_date
        stopLoss = self.stopLoss

        # 1. 取得並清洗股價資料
        df = yf.download(target_stock, start_date, end_date)
        df.rename(columns={'Close':'close', 'High':'high', 'Low':'low', 'Open':'open', 'Volume':'volume' }, inplace = True)

        # **關鍵修正：使用 .values.astype('float').squeeze() 確保 1D 陣列**
        closePrices = df['close'].values.astype('float').squeeze()
        
        # 2. 計算 BBANDS 指標
        UpperBand, MiddleBand, LowerBand = talib.BBANDS(
            closePrices, timeperiod=self.timeperiod, nbdevup=self.nbdevup, nbdevdn=self.nbdevdn
        )

        # 3. 變數初始化
        flage, buyPrice, sellPrice, winTime, lossTime, culReturn, transList, everyTranReturn, tradingDetails, tax = 0, 0, 0, 0, 0, 0, [], [], [], 0
        start_index = self.timeperiod # 從 BBANDS 有效值之後開始
        
        # 4. 買賣策略設定與交易 (逆勢邏輯)
        for x in range(start_index, len(closePrices)):
            current_close = closePrices[x]
            
            # --- 買入訊號 ---
            if flage == 0: 
                # 買入: 跌破下軌線 (超賣訊號)
                if current_close < LowerBand[x]:
                    buyPrice = current_close
                    tradingDetails.append(("買進日期 = ", str(df.iloc[x:x+1].index[0])[:11] , "買進價格 = ", format(buyPrice, ".2f")))
                    tax = tax + buyPrice * 0.001425 
                    flage = 1 

            # --- 賣出訊號 ---
            if flage == 1: 
                sellPrice = current_close
                
                # 賣出: 突破上軌線 (超買/獲利了結)
                if current_close > UpperBand[x]: 
                    tax = tax + sellPrice * 0.001425 + sellPrice*0.003
                    if ( sellPrice - buyPrice) > 0:
                        tradingDetails.append(("賣出日期 = ", str(df.iloc[x:x+1].index[0])[:11] , "賣出價格 = ", format(sellPrice, ".2f"), "賺", format(( sellPrice - buyPrice -tax),".2f"), format(( sellPrice - buyPrice -tax) / buyPrice, ".2%")))
                        winTime+=1 
                    else:
                        tradingDetails.append(("賣出日期 = ", str(df.iloc[x:x+1].index[0])[:11] , "賣出價格 = ", format(sellPrice, ".2f"), "賠", format(( sellPrice - buyPrice -tax),".2f"), format(( sellPrice - buyPrice -tax) / buyPrice, ".2%")))
                        lossTime+=1 
                    flage = 0
                    everyTranReturn.append(( sellPrice - buyPrice) - tax)
                    culReturn = culReturn + ( sellPrice - buyPrice) - tax
                    transList.append(culReturn)
                    tax = 0
                
                # 停損邏輯
                if stopLoss > 0 and flage == 1:
                    if (sellPrice - buyPrice -tax) / buyPrice < -stopLoss:
                        tax = tax + sellPrice * 0.001425 + sellPrice*0.003
                        tradingDetails.append(("賣出日期 = ", str(df.iloc[x:x+1].index[0])[:11] , "賣出價格 = ", format(sellPrice, ".2f"), "停損", format(( sellPrice - buyPrice -tax),".2f"), format(( sellPrice - buyPrice -tax) / buyPrice, ".2%"))) 
                        lossTime+=1
                        flage = 0
                        everyTranReturn.append(( sellPrice - buyPrice) - tax)
                        culReturn = culReturn + ( sellPrice - buyPrice) - tax
                        transList.append(culReturn)
                        tax = 0
                        
        # 5. 輸出報表 (呼叫父類別方法)
        self.printEveryTradingInfor(tradingDetails)
        self.printStatisticTradingInfor(culReturn, winTime, lossTime, closePrices[-1], closePrices[0], everyTranReturn)
        self.drawCumulativeReturnSeries(transList)
        return culReturn