# -*- coding: utf-8 -*-
"""macdTSClass.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F4CwdUQnBULr2pC-WWp3xTFy5Ruem09k
"""

import numpy as np
import pandas as pd
import talib
import yfinance as yf
from datetime import datetime
import matplotlib.pyplot as plt
import statistics
from parentTSClass import parentTSClass
# 假設 parentTSClass 已經在您的父類別檔案中定義


class macdTSClass(parentTSClass):
    # MACD 的快線、慢線和訊號線週期
    def __init__(self, target_stock, start_date, end_date, stopLoss, fastperiod=12, slowperiod=26, signalperiod=9):
        super().__init__(target_stock, start_date, end_date, stopLoss)
        self.fastperiod = fastperiod
        self.slowperiod = slowperiod
        self.signalperiod = signalperiod

    def tradingStrategy(self, target_stock=0, start_date=0, end_date=0, stopLoss=0):
        target_stock = self.target_stock
        start_date = self.start_date
        end_date = self.end_date
        stopLoss = self.stopLoss

        # 1. 取得並清洗股價資料
        df = yf.download(target_stock, start_date, end_date)
        df.rename(columns={'Close':'close', 'High':'high', 'Low':'low', 'Open':'open', 'Volume':'volume' }, inplace = True)

        # **關鍵修正：使用 .values.astype('float').squeeze() 確保 1D 陣列**
        closePrices = df['close'].values.astype('float').squeeze()
        
        # 2. 計算 MACD 指標
        DIF, MACD, HIST = talib.MACD(
            closePrices, fastperiod=self.fastperiod, slowperiod=self.slowperiod, signalperiod=self.signalperiod
        )

        # 3. 變數初始化
        flage, buyPrice, sellPrice, winTime, lossTime, culReturn, transList, everyTranReturn, tradingDetails, tax = 0, 0, 0, 0, 0, 0, [], [], [], 0
        start_index = self.slowperiod + self.signalperiod # 保守的起始點
        
        # 4. 買賣策略設定與交易
        for x in range(start_index, len(closePrices)):
            current_close = closePrices[x]
            if np.isnan(DIF[x]) or np.isnan(MACD[x]): continue

            # --- 買入訊號 (黃金交叉) ---
            if flage == 0: 
                if DIF[x-1] <= MACD[x-1] and DIF[x] > MACD[x]:
                    buyPrice = current_close
                    tradingDetails.append(("買進日期 = ", str(df.iloc[x:x+1].index[0])[:11] , "買進價格 = ", format(buyPrice, ".2f")))
                    tax = tax + buyPrice * 0.001425
                    flage = 1

            # --- 賣出訊號 (死亡交叉 + 停損) ---
            if flage == 1: 
                sellPrice = current_close
                
                # 賣出: 死亡交叉
                if DIF[x-1] >= MACD[x-1] and DIF[x] < MACD[x]:
                    tax = tax + sellPrice * 0.001425 + sellPrice*0.003
                    if ( sellPrice - buyPrice) > 0:
                        tradingDetails.append(("賣出日期 = ", str(df.iloc[x:x+1].index[0])[:11] , "賣出價格 = ", format(sellPrice, ".2f"), "賺", format(( sellPrice - buyPrice -tax),".2f"), format(( sellPrice - buyPrice -tax) / buyPrice, ".2%")))
                        winTime+=1 
                    else:
                        tradingDetails.append(("賣出日期 = ", str(df.iloc[x:x+1].index[0])[:11] , "賣出價格 = ", format(sellPrice, ".2f"), "賠", format(( sellPrice - buyPrice -tax),".2f"), format(( sellPrice - buyPrice -tax) / buyPrice, ".2%")))
                        lossTime+=1 
                    flage = 0
                    everyTranReturn.append(( sellPrice - buyPrice) - tax)
                    culReturn = culReturn + ( sellPrice - buyPrice) - tax
                    transList.append(culReturn)
                    tax = 0

                # 停損邏輯
                if stopLoss > 0 and flage == 1:
                    if (sellPrice - buyPrice -tax) / buyPrice < -stopLoss:
                        tax = tax + sellPrice * 0.001425 + sellPrice*0.003
                        tradingDetails.append(("賣出日期 = ", str(df.iloc[x:x+1].index[0])[:11] , "賣出價格 = ", format(sellPrice, ".2f"), "停損", format(( sellPrice - buyPrice -tax),".2f"), format(( sellPrice - buyPrice -tax) / buyPrice, ".2%"))) 
                        lossTime+=1
                        flage = 0
                        everyTranReturn.append(( sellPrice - buyPrice) - tax)
                        culReturn = culReturn + ( sellPrice - buyPrice) - tax
                        transList.append(culReturn)
                        tax = 0
                        
        # 5. 輸出報表 (呼叫父類別方法)
        self.printEveryTradingInfor(tradingDetails)
        self.printStatisticTradingInfor(culReturn, winTime, lossTime, closePrices[-1], closePrices[0], everyTranReturn) 
        self.drawCumulativeReturnSeries(transList)
        return culReturn