# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F-iDqNu5icuKNfrwcm5PqqWy2ufl95S-
"""

from google.colab import drive
drive.mount('/content/drive')

import sys
sys.path.append('/content/drive/MyDrive/W6')

import sys
sys.path.append('/content/drive/MyDrive/00-上課資料(學校HD)/W6/package')

# Commented out IPython magic to ensure Python compatibility.
# 步驟 1: 安裝 TA-Lib 系統依賴 (確保所有 C 函式庫就位)
!wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
!tar -xzf ta-lib-0.4.0-src.tar.gz
# %cd ta-lib
!./configure --prefix=/usr
!make
!make install
# %cd ..

# 步驟 2: 安裝 Python 綁定 (移除 -t 參數)
!pip install ta-lib

# 步驟 3: 重新啟動 Runtime (執行階段 -> 重新啟動執行階段)
# 確保新的環境配置被載入

# 步驟 4: 重新執行您的 import 程式碼

import numpy as np
import pandas as pd
import talib
import yfinance as yf
from datetime import datetime
import matplotlib.pyplot as plt
import statistics
from itertools import combinations
import warnings
warnings.filterwarnings('ignore') # 忽略 yfinance 的 FutureWarning

# =========================================================
# I. PARENT CLASS (包含所有統計修正)
# =========================================================
class parentTSClass:
    def __init__(self, target_stock, start_date, end_date, stopLoss):
        self.target_stock = target_stock
        self.start_date = start_date
        self.end_date = end_date
        self.stopLoss = stopLoss

    def printEveryTradingInfor(self, tradingDetails):
        print("--- 逐筆交易紀錄 (部分省略) ---")
        for i in tradingDetails[:5]:
            print(" ".join(map(str, i)))
        if len(tradingDetails) > 5:
             print("...")
        print("-" * 20)

    def printStatisticTradingInfor(self, culReturn, winTime, lossTime, lastClosePrice, firstClosePrice, everyTranReturn):
        if not everyTranReturn:
            print("無有效交易。")
            return

        print("========================================================================== ")
        print(f"最終淨報酬 = {format(culReturn, '.2f')} | 賺錢次數 = {winTime} | 虧損次數 = {lossTime}")

        if not np.isnan(firstClosePrice) and not np.isnan(lastClosePrice):
            print(f"買入持有 (Buy & Hold) = {format(lastClosePrice - firstClosePrice, '.2f')}")

        if len(everyTranReturn) >= 2:
            print(f"平均獲利 = {format(statistics.mean(everyTranReturn), '.2f')} | 獲利變異數 = {format(statistics.variance(everyTranReturn), '.2f')}")
        else:
            print("統計分析 (變異數/標準差) 需要至少兩筆交易數據。")

        print("========================================================================== ")

    def tradingStrategy(self): return 0 # 基類方法

STRATEGY_NAMES = ['ROC', 'MA', 'RSI', 'MACD', 'BBANDS']

# =========================================================
# II. 核心訊號計算函數 (已強化為最魯棒的 NumPy 數組操作)
# =========================================================
def calculate_signal_for_strategy(df, strategy_name):
    """
    為單一策略計算每日訊號 (+1: Buy, -1: Sell, 0: Hold)
    【已強化為最魯棒的 NumPy 數組操作】
    """
    df = df.copy()
    close_series = df['close'].ffill()

    if len(close_series) < 30 or close_series.isnull().all():
        df['Signal'] = 0
        return df['Signal']

    close_values = close_series.values # NumPy 陣列 for talib

    # 初始化訊號欄位
    df['Signal'] = 0

    # 策略計算區塊
    if strategy_name == 'ROC':
        ROC = talib.ROC(close_values, timeperiod=12)
        ROC = np.nan_to_num(ROC) # 將 NaN 轉為 0
        df['Signal'] = np.where(ROC > 0, 1, np.where(ROC < 0, -1, 0))

    elif strategy_name == 'MA':
        MA5 = talib.SMA(close_values, timeperiod=5)
        MA20 = talib.SMA(close_values, timeperiod=20)
        MA5 = np.nan_to_num(MA5)
        MA20 = np.nan_to_num(MA20)
        df['Signal'] = np.where(MA5 > MA20, 1, np.where(MA5 < MA20, -1, 0))

    elif strategy_name == 'RSI':
        RSI = talib.RSI(close_values, timeperiod=14)
        RSI_Series = pd.Series(np.nan_to_num(RSI), index=df.index)
        buy_cond = np.array((RSI_Series.shift(1) <= 30) & (RSI_Series > 30))
        sell_cond = np.array((RSI_Series.shift(1) >= 70) & (RSI_Series < 70))
        df['Signal'] = np.where(buy_cond, 1, np.where(sell_cond, -1, 0))

    elif strategy_name == 'MACD':
        DIF, MACD, HIST = talib.MACD(close_values, fastperiod=12, slowperiod=26, signalperiod=9)
        DIF_Series = pd.Series(np.nan_to_num(DIF), index=df.index)
        MACD_Series = pd.Series(np.nan_to_num(MACD), index=df.index)

        buy_cond = np.array((DIF_Series.shift(1) <= MACD_Series.shift(1)) & (DIF_Series > MACD_Series))
        sell_cond = np.array((DIF_Series.shift(1) >= MACD_Series.shift(1)) & (DIF_Series < MACD_Series))
        df['Signal'] = np.where(buy_cond, 1, np.where(sell_cond, -1, 0))

    elif strategy_name == 'BBANDS':
        Upper, Middle, Lower = talib.BBANDS(close_values, timeperiod=20, nbdevup=2, nbdevdn=2)
        Lower_Series = pd.Series(np.nan_to_num(Lower, nan=close_values.min()), index=df.index)
        Upper_Series = pd.Series(np.nan_to_num(Upper, nan=close_values.max()), index=df.index)

        buy_cond = np.array(close_series < Lower_Series)
        sell_cond = np.array(close_series > Upper_Series)
        df['Signal'] = np.where(buy_cond, 1, np.where(sell_cond, -1, 0))

    # 【最終確保】：將所有剩餘的 NaN 值設為 0
    df['Signal'].fillna(0, inplace=True)
    return df['Signal']

# =========================================================
# III. 核心回測函數：執行寬鬆傾向規則 (最終修正)
# =========================================================
def run_backtest_combo(combo_names, symbol, start_date, end_date):

    # 1. 數據下載與準備
    df = yf.download(symbol, start_date, end_date, progress=False)

    if df.empty or len(df) < 30:
        return 0

    df.rename(columns={'Close':'close', 'High':'high', 'Low':'low', 'Open':'open', 'Volume':'volume' }, inplace = True)

    # 2. 計算訊號並聚合
    N_combo = len(combo_names)
    signal_columns = []

    for name in combo_names:
        signal_col_name = f'{name}_Signal'
        df[signal_col_name] = calculate_signal_for_strategy(df.copy(), name)
        signal_columns.append(signal_col_name)

    df['Total_Signal'] = df[signal_columns].sum(axis=1)

    # 3. 交易執行
    flag = 0  # 0: 未持有, 1: 持有
    buyPrice = 0
    tax = 0
    culReturn = 0

    # 找到第一個非 NaN 的索引作為回測起點
    start_index = df['Total_Signal'].first_valid_index()
    if start_index is None:
        return 0

    start_idx_num = df.index.get_loc(start_index)

    # 獲取 Buy & Hold 基準點
    firstClosePrice = df.iloc[start_idx_num]['close']
    lastClosePrice = df.iloc[-1]['close']
    everyTranReturn = [] # 用於統計

    for x in range(start_idx_num, len(df)):
        current_close = df.iloc[x]['close']
        current_signal_sum = df.iloc[x]['Total_Signal']

        # A. 寬鬆買入條件 (淨訊號總和 >= 1)
        if flag == 0 and current_signal_sum >= 1:
            buyPrice = current_close
            tax = buyPrice * 0.001425
            flag = 1

        # B. 寬鬆賣出條件 (淨訊號總和 <= -1)
        elif flag == 1 and current_signal_sum <= -1:
            sellPrice = current_close
            tax += sellPrice * 0.001425 + sellPrice * 0.003
            profit = (sellPrice - buyPrice) - tax
            culReturn += profit
            everyTranReturn.append(profit)

            flag = 0
            buyPrice = 0
            tax = 0

    # 結束平倉
    if flag == 1:
        sellPrice = df.iloc[-1]['close']
        tax += sellPrice * 0.001425 + sellPrice * 0.003
        profit = (sellPrice - buyPrice) - tax
        culReturn += profit
        everyTranReturn.append(profit)

    return culReturn

# =========================================================
# IV. 主搜尋迴圈 (執行所有測試，含錯誤防禦)
# =========================================================
def run_full_search():
    # 1. 組合生成
    strategy_names = STRATEGY_NAMES
    all_combos = []
    for r in range(1, 4):
        all_combos.extend(list(combinations(strategy_names, r)))

    # 2. 定義回測情境 (包含競賽要求的三個趨勢)
    test_scenarios = {
        'Uptrend': {'symbol': '2330.TW', 'start': datetime(2013, 1, 1), 'end': datetime(2022, 12, 31)},
        'Sideways': {'symbol': '2412.TW', 'start': datetime(2013, 1, 1), 'end': datetime(2022, 12, 31)},
        'Downtrend': {'symbol': '2498.TW', 'start': datetime(2013, 1, 1), 'end': datetime(2022, 12, 31)}
    }

    # 將初始值設為確定的負數，避免極限浮點數比較錯誤
    best_results = {
        'Uptrend': {'Return': -10000.0, 'Combination': None},
        'Sideways': {'Return': -10000.0, 'Combination': None},
        'Downtrend': {'Return': -10000.0, 'Combination': None}
    }

    # 3. 執行搜尋
    for trend, params in test_scenarios.items():
        symbol = params['symbol']
        start_date = params['start']
        end_date = params['end']

        print(f"\n--- 開始搜尋: {trend} ({symbol}) --- 總共 {len(all_combos)} 種組合")

        for combo in all_combos:
            current_return = 0

            try:
                # 呼叫核心回測函數
                current_return = run_backtest_combo(combo, symbol, start_date, end_date)

            except ValueError as e:
                # 捕獲 Pandas 歧義錯誤
                if "The truth value of a Series is ambiguous" in str(e):
                    # 賦予極低報酬，確保它不會被選為最佳，並繼續執行
                    current_return = -10000.0
                else:
                    raise e # 遇到其他未知的 ValueError，需要重新拋出

            if current_return > best_results[trend]['Return']:
                best_results[trend]['Return'] = current_return
                best_results[trend]['Combination'] = combo

        print(f"✅ 該趨勢最佳組合 ({trend}): {best_results[trend]['Combination']} | 淨報酬: {best_results[trend]['Return']:.2f} 元")

    print("\n==========================================================")
    print("🏆 競賽結果彙總 🏆")
    print("==========================================================")
    for trend, result in best_results.items():
        print(f"{trend} ({test_scenarios[trend]['symbol']}):")
        print(f"  最高報酬: {result['Return']:.2f} 元")
        print(f"  策略組合: {result['Combination']}")

    print("\n請將這三個趨勢的最佳報酬填入繳交文件。")

# 執行總搜尋
run_full_search()