# -*- coding: utf-8 -*-
"""parentTSClass.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ld-vC44xzPtjIH0VttaC6c0UqeIK2BMF
"""

import numpy as np
import pandas as pd
import talib
import yfinance as yf
from datetime import datetime
import matplotlib.pyplot as plt
import statistics
import sys # 用於處理可能殘留的模組

class parentTSClass:
    def __init__(self, target_stock, start_date, end_date, stopLoss):
        # 關鍵修正：確保屬性賦值正確
        self.target_stock = target_stock
        self.start_date = start_date
        self.end_date = end_date 
        self.stopLoss = stopLoss

    # 1. 畫出股價序列圖 (功能已還原)
    def drawStockSeries(self, df, xLabel):
        df[['close']].plot(figsize=(7,3))
        plt.title(xLabel, size=15)
        plt.legend(loc = "best", fontsize=12)
        plt.show() # 關鍵：顯示圖表

    # 2. 畫出 MA 序列圖 (功能已還原)
    def drawMA5_10_20Series(self, xValues, yValues1, yValues2, yValues3, target_stock):
        plt.figure(figsize=(7,3))
        plt.title(target_stock, size=15)
        plt.plot(xValues,yValues1,'-', color = 'r', label="MA-5")
        plt.plot(xValues,yValues2,'+', color = 'g', label="MA-10")
        plt.plot(xValues,yValues3,'x', color = 'b', label="MA-20")
        plt.legend(loc = "best", fontsize=12)
        plt.show() # 關鍵：顯示圖表

    # 3. 印出逐筆交易資訊 (修正縮排和輸出格式)
    def printEveryTradingInfor(self, tradingDetails): 
        print("--- 逐筆交易紀錄 ---")
        for i in tradingDetails:
            print(" ".join(map(str, i)))
        print("-" * 20)

    # 4. 印出交易統計資訊 (修正 StatisticsError)
    def printStatisticTradingInfor(self, culReturn, winTime, lossTime, lastClosePrice, firstClosePrice, everyTranReturn):
        if not everyTranReturn:
            print("無有效交易。")
            return
            
        print("========================================================================== ")
        print(f"最終淨報酬 = {format(culReturn, '.2f')} | 賺錢次數 = {winTime} | 虧損次數 = {lossTime}")
        print(f"買入持有 (Buy & Hold) = {format(lastClosePrice - firstClosePrice, '.2f')}")
        
        if len(everyTranReturn) >= 2:
            print(f"最大獲利 = {format(max(everyTranReturn),'.2f')} | 最大虧損 = {format(min(everyTranReturn), '.2f')}")
            print(f"平均獲利 = {format(np.mean(everyTranReturn), '.2f')} | 獲利標準差 = {format(np.std(everyTranReturn), '.2f')}")
            print(f"平均獲利 (Stats) = {format(statistics.mean(everyTranReturn), '.2f')}")
            print(f"獲利變異數 = {format(statistics.variance(everyTranReturn), '.2f')}")
            print(f"獲利標準差 (Stats) = {format(statistics.stdev(everyTranReturn), '.2f')}")
        else:
            print(f"最大獲利 = {format(max(everyTranReturn),'.2f')} | 最大虧損 = {format(min(everyTranReturn), '.2f')}")
            print("統計分析 (變異數/標準差) 需要至少兩筆交易數據。")
            
        print("========================================================================== ")
        
    # 5. 畫出累計報酬圖 (功能已還原)
    def drawCumulativeReturnSeries(self, yValues1):
        plt.title("Cumulative Return", size=15)
        plt.xlabel('Transaction#')
        plt.ylabel('NT$')
        plt.plot(yValues1)
        plt.show() # 關鍵：顯示圖表
        
    # 6. 核心策略函數 (留給子類別覆寫)
    def tradingStrategy(self): 
        return 0