# -*- coding: utf-8 -*-
"""rsiTSClass.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xUJOVR9qzTZwYsNIha6697do76aJBNNc
"""

import numpy as np
import pandas as pd
import talib
import yfinance as yf
from datetime import datetime
import matplotlib.pyplot as plt
import statistics
from parentTSClass import parentTSClass
class rsiTSClass(parentTSClass):
    def __init__(self, target_stock, start_date, end_date, stopLoss, rsi_period=14, overbought=70, oversold=30):
        # 呼叫父類別的初始化方法
        super().__init__(target_stock, start_date, end_date, stopLoss) 
        self.rsi_period = rsi_period
        self.overbought = overbought
        self.oversold = oversold

    def tradingStrategy(self, target_stock=0, start_date=0, end_date=0, stopLoss=0):
        target_stock = self.target_stock
        start_date = self.start_date
        end_date = self.end_date
        stopLoss = self.stopLoss

        df = yf.download(target_stock, start_date, end_date)
        df.rename(columns={'Close':'close', 'High':'high', 'Low':'low', 'Open':'open', 'Volume':'volume' }, inplace = True)

        # 修正維度問題：確保 closePrices 始終是 1D 陣列
        closePrices = df['close'].values.astype('float').squeeze()
        RSI = talib.RSI(closePrices, timeperiod=self.rsi_period)

        # 變數初始化 (與您的其他策略保持一致)
        flage, buyPrice, sellPrice, winTime, lossTime, culReturn, transList, everyTranReturn, tradingDetails, tax = 0, 0, 0, 0, 0, 0, [], [], [], 0
        start_index = self.rsi_period 
        
        for x in range(start_index, len(closePrices)):
            current_close = closePrices[x]
            
            # ------------------- 買入訊號 -------------------
            if flage == 0: 
                # 買入: RSI 從超賣區 (30) 反彈，穿過 30 (逆勢買入)
                if RSI[x-1] <= self.oversold and RSI[x] > self.oversold:
                    buyPrice = current_close
                    tradingDetails.append(("買進日期 = ", str(df.iloc[x:x+1].index[0])[:11] , "買進價格 = ", format(buyPrice, ".2f")))
                    tax = tax + buyPrice * 0.001425
                    flage = 1

            # ------------------- 賣出訊號 -------------------
            if flage == 1: 
                sellPrice = current_close
                
                # 賣出: RSI 從超買區 (70) 回落，穿過 70 (逆勢賣出/獲利了結)
                if RSI[x-1] >= self.overbought and RSI[x] < self.overbought:
                    tax = tax + sellPrice * 0.001425 + sellPrice*0.003
                    if ( sellPrice - buyPrice) > 0:
                        tradingDetails.append(("賣出日期 = ", str(df.iloc[x:x+1].index[0])[:11] , "賣出價格 = ", format(sellPrice, ".2f"), "賺", format(( sellPrice - buyPrice -tax),".2f"), format(( sellPrice - buyPrice -tax) / buyPrice, ".2%")))
                        winTime+=1 
                    else:
                        tradingDetails.append(("賣出日期 = ", str(df.iloc[x:x+1].index[0])[:11] , "賣出價格 = ", format(sellPrice, ".2f"), "賠", format(( sellPrice - buyPrice -tax),".2f"), format(( sellPrice - buyPrice -tax) / buyPrice, ".2%")))
                        lossTime+=1 
                    flage = 0
                    everyTranReturn.append(( sellPrice - buyPrice) - tax)
                    culReturn = culReturn + ( sellPrice - buyPrice) - tax
                    transList.append(culReturn)
                    tax = 0
                
                # 停損邏輯
                if stopLoss > 0 and flage == 1:
                    if (sellPrice - buyPrice -tax) / buyPrice < -stopLoss:
                        tax = tax + sellPrice * 0.001425 + sellPrice*0.003
                        tradingDetails.append(("賣出日期 = ", str(df.iloc[x:x+1].index[0])[:11] , "賣出價格 = ", format(sellPrice, ".2f"), "停損", format(( sellPrice - buyPrice -tax),".2f"), format(( sellPrice - buyPrice -tax) / buyPrice, ".2%"))) 
                        lossTime+=1
                        flage = 0
                        everyTranReturn.append(( sellPrice - buyPrice) - tax)
                        culReturn = culReturn + ( sellPrice - buyPrice) - tax
                        transList.append(culReturn)
                        tax = 0
                        
        self.printEveryTradingInfor(tradingDetails) 
        self.printStatisticTradingInfor(culReturn, winTime, lossTime, closePrices[-1], closePrices[0], everyTranReturn)
        self.drawCumulativeReturnSeries(transList)
        return culReturn