# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P4t4i4bYvFQ0jxIW8CFH1cD1B0XTbGpi
"""

#Colab - 掛接雲端硬碟
from google.colab import drive
drive.mount('/content/drive')

import sys
sys.path.append('/content/drive/MyDrive/W6')

import sys
sys.path.append('/content/drive/MyDrive/W6/package')

import importlib
import parentTSClass # 匯入父類別模組

# ----------------------------------------------------
# Colab/Jupyter 環境強制重新載入模組
# ----------------------------------------------------
try:
    importlib.reload(parentTSClass)
    # 如果您的子類別也在單獨的檔案中，也要重新載入
    import maTSClass
    importlib.reload(maTSClass)
    import rocTSClass
    importlib.reload(rocTSClass)
except NameError:
    # 第一次執行時可能還沒有這些物件，可以忽略
    pass
# ----------------------------------------------------

import importlib
import parentTSClass

# 強制重新載入父類別，確保讀取到修正後的版本
importlib.reload(parentTSClass)

# ... 接下來是您的所有 import ...
from maTSClass import maTSClass
from rocTSClass import rocTSClass
# ... 接下來是您的所有策略定義和執行 ...

from maTSClass import maTSClass
from rocTSClass import rocTSClass
from rsiTSClass import rsiTSClass
from bollTSClass import bollTSClass
from macdTSClass import macdTSClass
from datetime import datetime
target_stock="2498.TW"
start_date=datetime(2021, 1, 1)
end_date = datetime(2021, 7, 19)
stopLoss = 0.1
def calcuateCulReturn(ts):
  return ts.tradingStrategy()
ts1 = maTSClass(target_stock, start_date, end_date, stopLoss)
print("CulReturn of TS1:", calcuateCulReturn(ts1))
ts2 = rocTSClass(target_stock, start_date, end_date, stopLoss)
print("CulReturn of TS2:", calcuateCulReturn(ts2))
ts3 = rsiTSClass(target_stock, start_date, end_date, stopLoss)
print("CulReturn of TS3 (RSI):", calcuateCulReturn(ts3))
ts4 = bollTSClass(target_stock, start_date, end_date, stopLoss)
print("CulReturn of TS5 (BBANDS):", calcuateCulReturn(ts4))
ts5 = macdTSClass(target_stock, start_date, end_date, stopLoss)
print("CulReturn of TS4 (MACD):", calcuateCulReturn(ts5))